Repository ovh-ux/component-rollup-config, pull requests merged in 2018-11, with the labels that each got.

#18 fix(plugins.translations-xml): apply toString if text is a number
  src/plugins/translation-xml.js
Labels: bug

#20 Package files entry
  package.json
Labels: bug, enhancement

#21 fix(translation-xml): rollback to regex to handle malformed xml
  package.json
  src/plugins/translation-xml.js
  test/test.js
  yarn.lock
Labels: bug

#22 feat(plugins): manage multiple formats instead of xml only
  README.md
  src/plugins/translation-inject.js
  src/plugins/translation-ui-router.js
  src/plugins/translation-utils.js
Labels: enhancement

#23 fix: remove unused rollup-plugin-less dependencie
  package.json
  yarn.lock
Labels: bug

#24 feat(plugins): add less and sass rollup plugins
  package.json
  src/index.js
  yarn.lock
Labels: enhancement

#26 fix(deps): move babel-preset-env from devDeps to dependencies
  package.json
Labels: bug

#27 fix(targets): refactor config targets
  README.md
  package.json
  src/index.js
  yarn.lock
Labels: enhancement

#28 fix(plugins): test module.default in injections
  src/plugins/translation-utils.js
Labels: bug
