Repository ovh-ux/component-rollup-config, pull requests merged in 2018-10, with the labels that each got.

#1 docs: update readme file
  README.md
Labels: enhancement

#2 build: update package.json file
  package.json
Labels: enhancement

#6 Full rewrite, using AST and translation injection
  .eslintrc
  .eslintrc.json
  index.js
  package.json
  plugins/translations.js
  plugins/ui-router-translations.js
  src/index.js
  src/plugins/translation-inject.js
  src/plugins/translation-ui-router.js
  src/plugins/translation-utils.js
  src/plugins/translation-xml.js
  test/test.js
  yarn.lock
Labels: bug, enhancement

#7 refactor: remove duplicate lint-staged and husky configuration
  package.json
Labels: enhancement

#8 refactor(commitlint): switch to json format as configuration file
  .commitlintrc.js
  .commitlintrc.json
Labels: enhancement

#9 test(translation-xml): use template string
  test/test.js
Labels: enhancement

#10 docs(readme): add some badges
  README.md
Labels: enhancement

#11 fix(deps): remove translations-build-tools dependency
  package.json
  yarn.lock
Labels: bug

#12 Feat/plugins export
  package.json
  src/index.js
  src/plugins/translation-xml.js
  yarn.lock
Labels: enhancement

#14 docs(readme): minor improvements
  README.md
Labels: enhancement

#15 fix(translation-xml): filter text
  src/plugins/translation-xml.js
  test/test.js
Labels: bug

#16 fix(filter): add filtering boolean option
  src/plugins/translation-inject.js
  src/plugins/translation-ui-router.js
  src/plugins/translation-xml.js
Labels: bug

#17 fix(normalizepath): use slash lib to ensure no back slash on windows
  package.json
  src/plugins/translation-utils.js
  yarn.lock
Labels: bug
